server:
  port: 5555

spring:
  profiles:
    active: "dev"


    
  main:
    banner-mode: "off"  
    
---
spring:
  profiles: dev
  cloud:
    config:
      server:
        git:
          uri: git@github.com:hiteshjoshi1/microservice-docker-cart-config.git
        health:
          repositories:
             customer-service:
              label: master
             discovery-service:
               label: master

eureka:
  instance:
    hostname: configserver
    preferIpAddress: true 
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:1111/eureka/

management:
   security:
     enabled: false
---
 # Using file system based repository for Docker
 # had some issue accessing git through SSH from my linux VM
spring:
  profiles: docker
  cloud:
    config:
      server:
        git:
          uri: file:/data/microservice-docker-cart-config
        health:
          repositories:
             customer-service:
              label: master
             discovery-service:
               label: master
eureka:
  instance:
    hostname: configserver
    preferIpAddress: true 
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://eureka:1111/eureka/
      
management:
   security:
     enabled: false      
      
