#notice the use of profiles one for localhost, one for docker
spring:
  profiles:
    active: "dev"
  main:
    banner-mode: "off"  
server:
  port: 2222 #${customer.port}     
    
---

spring:
  profiles: dev
  freemarker:
    enabled: false           # Ignore Eureka dashboard FreeMarker templates
  jpa:
    hibernate:
      ddl-auto: none  
  datasource:
    url: jdbc:mysql://localhost:3306/microservices_cust
    username: root
    password: test
     
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:${customer.discovery.port}/eureka/ # using eureka instead of localhost
  instance:
    leaseRenewalIntervalInSeconds: 5   # DO NOT DO THIS IN PRODUCTION
    preferIpAddress: true

    
---

spring:
  profiles: docker
  freemarker:
    enabled: false           # Ignore Eureka dashboard FreeMarker templates
  jpa:
    hibernate:
      ddl-auto: none  
  datasource:   #docker instance of mysql
    url: jdbc:mysql://localhost:3306/microservices_cust
    username: root
    password: test 
    
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:${customer.discovery.port}/eureka/ # using eureka instead of localhost
  instance:
    leaseRenewalIntervalInSeconds: 5   # DO NOT DO THIS IN PRODUCTION
    preferIpAddress: true

  
   


