#notice the use of profiles one for localhost, one for docker
spring:
  profiles:
    active: "dev"
  main:
    banner-mode: "off"  
    
---

spring:
  profiles: dev
  application:
     name: customer-service
  freemarker:
    enabled: false           # Ignore Eureka dashboard FreeMarker templates
  jpa:
    hibernate:
      ddl-auto: none  
  datasource:
    url: jdbc:mysql://localhost:3306/microservices_cust
    username: root
    password: test 
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1111/eureka/ # using eureka instead of localhost
  instance:
    leaseRenewalIntervalInSeconds: 5   # DO NOT DO THIS IN PRODUCTION
    metadataMap:
    instanceId: customer:${random.value}
  preferIpAddress: true
server:
  port: 2222    

    
---

spring:
  profiles: docker
  application:
     name: customer-service
  freemarker:
    enabled: false           # Ignore Eureka dashboard FreeMarker templates
  jpa:
    hibernate:
      ddl-auto: none  
  datasource:   #docker instance of mysql
    url: jdbc:mysql://localhost:32768/microservices_cust
    username: root
    password: test 
    
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:1111/eureka/ # using eureka instead of localhost
  instance:
    leaseRenewalIntervalInSeconds: 5   # DO NOT DO THIS IN PRODUCTION
    metadataMap:
    instanceId: customer:${random.value}
  preferIpAddress: true

 server:
  port: 2222    
   


