eureka:
 image: springcloud/eureka
 container_name: eureka
 ports:
 - "1111:1111"
 net: "microservicesnet"
customer1:
 image: hiteshjoshi1/microservice-docker-cart-example
 container_name: customer1
 hostname: customer1
 net: "microservicesnet"
 ports:
 - "2222:8080"
 volumes:
 - C:\\Users\\hitjoshi\\Desktop\\Microservices\\ci_output:/data
 command: -jar -Dspring.datasource.url=jdbc:mysql://docker-mysql/microservices_cust -Dspring.datasource.password=test /data/customer-0.0.1-SNAPSHOT.jar
inventory1:
 image: hiteshjoshi1/microservice-docker-cart-example
 container_name: inventory1
 hostname: inventory1
 net: "microservicesnet"
 ports:
 - "3333:8080"
 volumes:
 - C:\\Users\\hitjoshi\\Desktop\\Microservices\\ci_output:/data
 command: -jar -Dspring.datasource.url=jdbc:mysql://docker-mysql/microservices_prod -Dspring.datasource.password=test /data/inventory-0.0.1-SNAPSHOT.jar
invoice1:
 image: hiteshjoshi1/microservice-docker-cart-example
 container_name: invoice1
 hostname: invoice1
 net: "microservicesnet"
 ports:
 - "4444:8080"
 volumes:
 - C:\\Users\\hitjoshi\\Desktop\\Microservices\\ci_output:/data
 command: -jar -Dspring.datasource.url=jdbc:mysql://docker-mysql/microservices_invoice -Dspring.datasource.password=test /data/invoice-0.0.1-SNAPSHOT.jar