eureka:
 image: hiteshjoshi1/microservice-docker-cart-example
 container_name: eureka
 hostname: eureka
 net: "microservicesnet"
 ports:
 - "1111:1111"
 volumes:
 - /home/hitesh/jarloc:/data
 command: -jar -Dspring.profiles.active=docker /data/servicediscovery-0.0.1-SNAPSHOT.jar
customer1:
 image: hiteshjoshi1/microservice-docker-cart-example
 net: "microservicesnet"
 ports:
 - "2222:2222"
 volumes:
 - /home/hitesh/jarloc:/data
 links:
  - docker-mysql
 command: -jar -Dspring.profiles.active=docker /data/customer-0.0.1-SNAPSHOT.jar
inventory1:
 image: hiteshjoshi1/microservice-docker-cart-example
 net: "microservicesnet"
 ports:
 - "3333:3333"
 volumes:
 - /home/hitesh/jarloc:/data
 links:
  - docker-mysql
 command: -jar -Dspring.profiles.active=docker /data/inventory-0.0.1-SNAPSHOT.jar
invoice1:
 image: hiteshjoshi1/microservice-docker-cart-example
 net: "microservicesnet"
 ports:
 - "4444:4444"
 volumes:
 - /home/hitesh/jarloc:/data
 links:
  - docker-mysql
 command: -jar -Dspring.profiles.active=docker  /data/invoice-0.0.1-SNAPSHOT.jar
