#notice the use of profiles one for localhost, one for docker
spring:
  profiles:
    active: "dev"
  main:
    banner-mode: "off"  
  freemarker:
    enabled: false           # Ignore Eureka dashboard FreeMarker templates

  sleuth:
    enabled: false
     
eureka:
   instance:
       leaseRenewalIntervalInSeconds: 5   # DO NOT DO THIS IN PRODUCTION
       preferIpAddress: true 
  
server:
  port: 9411
        
---

spring:
  profiles: dev
 
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:${discovery.port}/eureka/ # using eureka instead of localhost


    
---

spring:
  profiles: docker
  rabbitmq:
   host: rabbitmq
   port: 5672
   username: guest
   password: guest
  jpa:
    hibernate:
      ddl-auto: none  
 # datasource:
 #   url: jdbc:mysql://docker-mysql/zipkin
 #   username: root
 #   password: test
 #   initialize: true
 #   continueOnError: true     

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:${discovery.port}/eureka/ # using eureka instead of localhost

    
