#notice the use of profiles one for localhost, one for docker
spring:
  profiles:
    active: "dev"
  main:
    banner-mode: "off"  

---

spring:
  profiles: dev
  thymeleaf:
    enabled: false
  
eureka:
  instance:
    hostname: localhost
  client:  # Not a client, don't register with yourself
    registerWithEureka: false
    fetchRegistry: false    
server:
  port: 1111
    
---

spring:
  profiles: docker
  thymeleaf:
    enabled: false
eureka:
  instance:
    hostname: localhost
  client:  # Not a client, don't register with yourself
    registerWithEureka: false
    fetchRegistry: false

server:
  port: 1111    