#notice the use of profiles one for localhost, one for docker
spring:
  profiles:
    active: "dev"
  main:
    banner-mode: "off"  
eureka:
   instance:
       leaseRenewalIntervalInSeconds: 5   # DO NOT DO THIS IN PRODUCTION
       preferIpAddress: true 
  
server:
  port: ${invoice.port}    
        
---

spring:
  profiles: dev
  freemarker:
    enabled: false           # Ignore Eureka dashboard FreeMarker templates
  jpa:
    hibernate:
      ddl-auto: none  
  datasource:
    url: jdbc:mysql://localhost:3306/microservices_invoice
    username: root
    password: test 
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:${invoice.discovery.port}/eureka/ # using eureka instead of localhost


    
---

spring:
  profiles: docker
  freemarker:
    enabled: false           # Ignore Eureka dashboard FreeMarker templates
  jpa:
    hibernate:
      ddl-auto: none  
  datasource:   #docker instance of mysql
    url: ${invoice.docker.datasource}   #jdbc:mysql://localhost:32768/microservices_invoice
    username: root
    password: test 
    
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:${invoice.discovery.port}/eureka/ # using eureka instead of localhost

